server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/productapi/**
          filters:
            - AuthenticationFilter
        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/couponapi/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0 # Captures 100% of requests
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
app:
  security:
    user: "gilvan"
    pass: "master123"
    # The secret must be at least 32 characters long for the HS256 algorithm
    jwt-secret: ${JWT_SECRET:this_is_a_very_secure_and_long_key_for_my_master_project}